### ISSUE TITLE
Problem to compile on Linux Mint 19.1

### ISSUE THREAD

**Issue by nicolalandro** [geontime/redkite#8]
I use the guide:
```
...
cd build
cmake ../
make
```
And than I get the error:
```
[  2%] Building CXX object CMakeFiles/redkite.dir/src/RkCairoGraphicsBackend.cpp.o
[  4%] Building CXX object CMakeFiles/redkite.dir/src/RkCairoImageBackendCanvas.cpp.o
[  6%] Building CXX object CMakeFiles/redkite.dir/src/RkWidget.cpp.o
[  8%] Building CXX object CMakeFiles/redkite.dir/src/RkWidgetImpl.cpp.o
[ 10%] Building CXX object CMakeFiles/redkite.dir/src/RkMain.cpp.o
[ 12%] Building CXX object CMakeFiles/redkite.dir/src/RkEventQueue.cpp.o
In file included from /home/mint/geonkick/LIB/redkite/src/RkEventQueue.cpp:25:0:
/home/mint/geonkick/LIB/redkite/include/impl/RkEventQueueImpl.h:76:14: error: ‘unordered_map’ in namespace ‘std’ does not name a template type
         std::unordered_map<unsigned long long int, RkWidget*> windowIdsMap;
              ^
CMakeFiles/redkite.dir/build.make:127: set di istruzioni per l'obiettivo "CMakeFiles/redkite.dir/src/RkEventQueue.cpp.o" non riuscito
make[2]: *** [CMakeFiles/redkite.dir/src/RkEventQueue.cpp.o] Errore 1
CMakeFiles/Makefile2:138: set di istruzioni per l'obiettivo "CMakeFiles/redkite.dir/all" non riuscito
make[1]: *** [CMakeFiles/redkite.dir/all] Errore 2
Makefile:129: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
```

**Comment by iurienistor** [comment]
Hi! Thank you. I'll check the issue.

**Comment by iurienistor** [comment]
I have just installed a fresh Linux Mint 19.1 and following the build instruction I could build Redkite without problems. Also, I could build Geonkick too. The error above means that probably your C++ build setup is not correct or it is using a different compiler (or C++ std version). If you have problems building it, you can get the Geonkick binary from here: https://github.com/geontime/geonkick/releases/download/v1.9.2/geonkick-1.9.2_GNU+Linux_64bit.zip

**Comment by nicolalandro** [comment]
Taks you. I can run the geonkick but only after exec this:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get install libstdc++6
```
